name: Deployment
 
on:
  push:
    branches:
      - main
 
jobs:
  webapp:
    runs-on: ubuntu-latest    
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
 
      - name: Publish authserver
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: webapp
          FOLDER: webapp
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "authserver: ({sha}) {msg}"